package com.rainsoft;

import java.awt.Color;
import sas.swing.MultiLineLabel;

public class MateriaPanel extends javax.swing.JPanel {

    /**
     * Creates new form Materia
     */
    public int index;

    public void setIndex(int i) {
        index = i;
    }

    public int getIndex() {
        return index;
    }

    public MateriaPanel() {
        initComponents();
    }

    public MateriaPanel(String text) {
        initComponents();
        jLabelTitulo.setText(text);
    }

    public void setText(String text) {
        jLabelTitulo.setText(text);
    }

    public String getText() {
        return jLabelTitulo.getText();
    }

    public void setDescricao(String text) {
        this.setToolTipText(text);
    }

    public void setColor(int r, int g, int b) {
        this.jLabelImagem.setBackground(new Color(r, g, b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagem = new javax.swing.JLabel();
        jLabelTitulo = new MultiLineLabel();
        jLabelBackground = new javax.swing.JLabel();

        setToolTipText("Lorem Ipsum");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(275, 102));
        setMinimumSize(new java.awt.Dimension(275, 102));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(275, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagem.setBackground(new java.awt.Color(204, 255, 204));
        jLabelImagem.setToolTipText("");
        jLabelImagem.setOpaque(true);
        add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 10));

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setMaximumSize(new java.awt.Dimension(20, 21));
        jLabelTitulo.setMinimumSize(new java.awt.Dimension(20, 21));
        jLabelTitulo.setPreferredSize(new java.awt.Dimension(20, 21));
        jLabelTitulo.setVerifyInputWhenFocusTarget(false);
        jLabelTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTituloMouseClicked(evt);
            }
        });
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 70));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/Nota.png"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(271, 110));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(271, 110));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(271, 110));
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTituloMouseClicked

    }//GEN-LAST:event_jLabelTituloMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
