/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rainsoft;

import sas.swing.MultiLineLabel;

/**
 *
 * @author jonas
 */
public class MateriaPanel extends javax.swing.JPanel {

    /**
     * Creates new form Materia
     */
    public MateriaPanel() {
        initComponents();
    }
    
    public MateriaPanel(String text) {
        initComponents();
        jLabelTitulo.setText(text);
    }
    
    public void setText(String text) {
        jLabelTitulo.setText(text);
    }
    
    public String getText() {
        return jLabelTitulo.getText();
    }
    
    /*public void setImage(String path) {
    jLabelTitulo.setIcon(icon);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagem = new javax.swing.JLabel();
        jLabelTitulo = new MultiLineLabel();
        jLabelBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(271, 110));
        setMinimumSize(new java.awt.Dimension(271, 110));
        setPreferredSize(new java.awt.Dimension(271, 110));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagem.setBackground(new java.awt.Color(255, 51, 0));
        jLabelImagem.setToolTipText("");
        jLabelImagem.setOpaque(true);
        add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 87, 87));

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.");
        jLabelTitulo.setToolTipText("");
        jLabelTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setVerifyInputWhenFocusTarget(false);
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 27, 180, 70));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/Aba.png"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(271, 110));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(271, 110));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(271, 110));
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
