/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rainsoft;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author cicer
 */
public class NovoLembrete extends javax.swing.JFrame {

    /**
     * Creates new form GerenciaLembrete
     */
    public NovoLembrete() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloAba = new javax.swing.JLabel();
        jTextLembrete = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Data = new javax.swing.JLabel();
        jFormattedData = new javax.swing.JFormattedTextField();
        campoData = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jFormattedHora = new javax.swing.JFormattedTextField();
        CampoHora = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TituloAba.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 26)); // NOI18N
        TituloAba.setForeground(new java.awt.Color(62, 62, 62));
        TituloAba.setText("Novo Lembrete");
        getContentPane().add(TituloAba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jTextLembrete.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextLembrete.setForeground(new java.awt.Color(77, 76, 76));
        jTextLembrete.setText("Digite o Título");
        jTextLembrete.setBorder(null);
        jTextLembrete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextLembreteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextLembreteFocusLost(evt);
            }
        });
        jTextLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLembreteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextLembrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 570, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 570, 20));

        Data.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        Data.setForeground(new java.awt.Color(50, 48, 48));
        Data.setText("Data");
        getContentPane().add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jFormattedData.setBorder(null);
        jFormattedData.setForeground(new java.awt.Color(77, 76, 76));
        jFormattedData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedData.setText("16/12/2021");
        jFormattedData.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jFormattedData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedDataFocusLost(evt);
            }
        });
        getContentPane().add(jFormattedData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 40));

        campoData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/campos.png"))); // NOI18N
        getContentPane().add(campoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        Hora.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        Hora.setForeground(new java.awt.Color(53, 53, 53));
        Hora.setText("Hora");
        Hora.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                HoraComponentRemoved(evt);
            }
        });
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 20));

        jFormattedHora.setBorder(null);
        jFormattedHora.setForeground(new java.awt.Color(77, 76, 76));
        jFormattedHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedHora.setText("21:15");
        jFormattedHora.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jFormattedHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedHoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedHoraFocusLost(evt);
            }
        });
        jFormattedHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 40));

        CampoHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/campos.png"))); // NOI18N
        getContentPane().add(CampoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/adicionar.png"))); // NOI18N
        jButtonAdd.setToolTipText("Adicionar");
        jButtonAdd.setBorder(null);
        jButtonAdd.setContentAreaFilled(false);
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 50, 50));

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/cancelar.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.setContentAreaFilled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rainsoft/images/telaPadraoLembrete.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLembreteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLembreteActionPerformed

    private void jTextLembreteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextLembreteFocusGained
        // TODO add your handling code here:
        if (jTextLembrete.getText().equals("Digite o Título" + "")) {
            jTextLembrete.setText("");
            jTextLembrete.setForeground(new Color(77,76,76));
        }
    }//GEN-LAST:event_jTextLembreteFocusGained

    private void jTextLembreteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextLembreteFocusLost
        // TODO add your handling code here:
        if (jTextLembrete.getText().equals("")) {
            jTextLembrete.setText("Digite o Título" + "");
            jTextLembrete.setForeground(new Color(77,76,76));
        }
    }//GEN-LAST:event_jTextLembreteFocusLost

    private void jFormattedDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedDataFocusGained
        // TODO add your handling code here:
        if (jFormattedData.getText().equals("16/12/2021" + "")) {
            jFormattedData.setText("");
            jFormattedData.setForeground(new Color(77,76,76));
        }
    }//GEN-LAST:event_jFormattedDataFocusGained

    private void jFormattedHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedHoraActionPerformed

    private void jFormattedHoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedHoraFocusGained
        // TODO add your handling code here:
        if (jFormattedHora.getText().equals("21:15" + "")) {
            jFormattedHora.setText("");
            jFormattedHora.setForeground(new Color(77,76,76));
        }
    }//GEN-LAST:event_jFormattedHoraFocusGained

    private void jFormattedDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedDataFocusLost
        // TODO add your handling code here:
        if (jFormattedData.getText().equals("")) {
            jFormattedData.setText("16/12/2021" + "");
            jFormattedData.setForeground(new Color(77,76,76));
        }
    }//GEN-LAST:event_jFormattedDataFocusLost

    private void jFormattedHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedHoraFocusLost
        // TODO add your handling code here:
        if (jFormattedHora.getText().equals("")) {
            jFormattedHora.setText("21:15" + "");
            jFormattedHora.setForeground(new Color(77,76,76));
        }
    }//GEN-LAST:event_jFormattedHoraFocusLost

    private void HoraComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_HoraComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraComponentRemoved

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoLembrete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoLembrete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampoHora;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel TituloAba;
    private javax.swing.JLabel campoData;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JFormattedTextField jFormattedData;
    private javax.swing.JFormattedTextField jFormattedHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextLembrete;
    // End of variables declaration//GEN-END:variables
}
